version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@6.15.3
jobs:
  build:
    working_directory: ~/league-matchmaking-frontend
    docker:
      - image: circleci/node:15.8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: angular-build
          command: npm run build --prod
      - run:
          name: angular-test
          command: npm run test --single-run --no-progress
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      - run:
          name: angular-lint
          command: npm run lint
      # - store_artifacts:
      #     path: tslint.xml
      #     prefix: lint

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: common
          create-repo: true
          repo: circleci-league-matchmaking-frontend
          tag: "$CIRCLE_SHA1"