version: 2
jobs:
  build:
    working_directory: ~/league-matchmaking-frontend
    docker:
      - image: circleci/node:15.8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.lock" }}
          paths:
            - ./node_modules
      - run:
          name: angular-build
          command: npm run build --prod
      - run:
          name: angular-test
          command: npm run test --single-run --no-progress
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      - run:
          name: angular-lint
          command: npm run lint
      # - store_artifacts:
      #     path: tslint.xml
      #     prefix: lint